### DISCUSSION TITLE
Provider type should be a key value in the config of an api, not the name itself

### DISCUSSION THREAD

**Discussion by sheldonhull** [charmbracelet/mods#429] [Ideas]
From what I can see, I can't set `azure` key twice, and if I change one to `azureopenai` it no longer recognizes it's an azure openai type right?

If so this means we should add a new provider key value 

```yaml

apis:
  azure:
    type: azure-openai
    base-url: <foo>
  azureopenai:
    type: azure-openai
    base-url: <different url and token for this model due to regional limitations>
```

Is this a correct assessment or is there something I can do to accomplish this in current config?
