### ISSUE TITLE
Allow copy code snippets to clipboard

### ISSUE THREAD

**Issue by rkintzi** [charmbracelet/mods#134]
I would appreciate it if there were a "--copy" option that could accept an optional integer argument specifying which code snippet (counting from the end of the conversation) to copy to the clipboard.

**Comment by zachatrocity** [comment]
With the mods flags `-q` and `-r` along with some prompting you could pipe your mods response into something like pbcopy like so:

```
mods -q -r "Give me only a one liner bash command to list the current processes running on port 3000." | pbcopy
```

Result from clipboard:

```
`lsof -i :3000`
```

I can't get rid of the backticks from mods but of course we could get rid of them with `tr`:

```
mods -q -r "Give me only a one liner bash command to list the current processes running on port 3000. No other info"  | tr -d '`' | pbcopy 
```

Results in:

```
lsof -i :3000
```

This is a handy snippet so you could just alias it in your bashrc:

```
alias copy="tr -d '\`' | pbcopy"
```

and finally use it like so:

```
mods -q -r "Give me only a one liner bash command to list the current processes running on port 3000. No other info" | copy
```

Your milage may very with the prompt. You could probably ensure more consistant results with a custom prompt

**Comment by caarlos0** [comment]
with the new roles feature, you can add something like this to your `mods --settings`:

```yaml
roles:
  "cmd":
    - you provide shell commands to resolve common questions
    - the commands don't need any explaining
    - commands should preferably be one-liners
```

and then

```sh 
mods --raw --role bash list all processes on port 3000 | pbcopy
```
