### ISSUE TITLE
How to use the new GPT-4-Turbo-models

### ISSUE THREAD

**Issue by toadle** [charmbracelet/mods#148]
Hey everybody, 

just for everybody looking, here is how to use the new `gpt-4-1106-preview` ("GPT-4-Turbo") model with `mods`: 

Type `mods --settings`

Now edit this presented file as follows: 

Add a new model-settings for `gpt-4-1106-preview`:
```
apis:
  openai:
    base-url: https://api.openai.com/v1
    api-key-env: OPENAI_API_KEY
    models:
      gpt-4-1106-preview:
        aliases: ["4t"]
        max-input-chars: 350000
        fallback: gpt-4
```

Now at the very top of the file change the `default-model`:

```
default-model: gpt-4-1106-preview
```

Save and exit the editor.

You can verify your change by trying something like this: 

`mods "What is your knowledge cutoff?"`

The answer should mention April 2023, because that is where GPT-4 Turbo cuts off.

```
  My knowledge is updated until April 2023. Any events or developments that
  have occurred after this time may not be included in my responses. If you
  have questions about anything that has happened after my knowledge cutoff,
  it is advisable to consult the latest sources for the most recent
  information.
```
