### ISSUE TITLE
Is it proper way to configure gpt-4-1106-preview in `mods --settings` ?

### ISSUE THREAD

**Issue by gwpl** [charmbracelet/mods#164]
Is it proper way to configure gpt-4-1106-preview?

```
$ mods --settings

# Default model (gpt-3.5-turbo, gpt-4, ggml-gpt4all-j...).
#default-model: gpt-4
default-model: gpt-4-1106-preview
(...)
# Default character limit on input to model.
#max-input-chars: 12250
max-input-chars: 398000
(...)
apis:
  openai:
    base-url: https://api.openai.com/v1
    api-key-env: OPENAI_API_KEY
    models:
(...)
      gpt-4-32k:
        aliases: ["32k"]
        max-input-chars: 98000
        fallback: gpt-4
      gpt-4-1106-preview:
        aliases: ["128k"]
        max-input-chars: 392000
        fallback: gpt-4-1106-preview
(...)
```

Also, maybe add it as option to default config now? After all it's one of available models?

(Or maybe make a flag `mods --update-settings-with-curent-models` that would fetch info about new models (from repo or via API...?)

**Comment by MadBomber** [comment]
This is how I have mind configured:

```yaml
apis:
  openai:
    base-url: https://api.openai.com/v1
    api-key-env: OPENAI_API_KEY
    models:
      gpt-4-1106-preview:
        aliases: ["128k"]
        max-input-chars: 128000
        fallback: gpt-4-32k
```
