### ISSUE TITLE
support perplexity 

### ISSUE THREAD

**Issue by caarlos0** [charmbracelet/mods#201]
Rauch created `p.sh` to use perplexity in the term: https://gist.github.com/rauchg/c5f0b1dc245ad95c593de8336aa382ac

Seems easy enough to integrate into mods, too

**Comment by bradyjoslin** [comment]
With this configuration in `mods` settings was able to get responses from Perplexity's API.

``` yml
# -- mods.yml --
# Aliases and endpoints for OpenAI compatible REST API.
apis:
  perplexity:
    base-url: https://api.perplexity.ai
    api-key:
    api-key-env: PERPLEXITY_API_KEY
    models:
      sonar-medium-online:
        aliases: ["perplexity", "p"]
        max-input-chars: 16384
        fallback:
```

However, larger responses were problematic, becoming nonsensical and poorly formatted.  Cloned down the repo and omitting some of the properties for `ChatCompletionRequest` fixes, so added this conditional.

``` go
// mods.go
req := openai.ChatCompletionRequest{
	Model:    mod.Name,
	Messages: m.messages,
	Stream:   true,
}

if mod.API != "perplexity" {
	req.Temperature = noOmitFloat(cfg.Temperature)
	req.TopP = noOmitFloat(cfg.TopP)
	req.Stop = cfg.Stop
	req.MaxTokens = cfg.MaxTokens
	req.ResponseFormat = responseFormat(cfg)
}

stream, err := client.CreateChatCompletionStream(ctx, req)
```

Can give a PR if this change is considered desired and suitable.
