### ISSUE TITLE
OpenAI Compatible API (together.xyz) gives status: 404 after ugrading mods.

### ISSUE THREAD

**Issue by ezynda3** [charmbracelet/mods#206]
I recently added together's OpenAI compatible API to my mods config
```yaml
together:
    api-key:
    api-key-env: TOGETHER_API_KEY
    base-url: https://api.together.xyz/v1
    models:
      mistralai/Mixtral-8x7B-Instruct-v0.1:
        aliases: ["mixtral"]
        max-input-chars: 12250
        fallback:
      snorkelai/Snorkel-Mistral-PairRM-DPO:
        aliases: ["snorkel"]
        max-input-chars: 12250
        fallback:
```
It was working just fine until I upgraded mods to `v1.2.1`.

Now whenever I try to run one of those models e.g. `mods -m mixtral hello` I get the following error.

```
   ERROR  There was a problem with the together API request.

  error, status code: 400, message: %!s(<nil>)
```
