### ISSUE TITLE
Feature request: Support patterns from external resources

### ISSUE THREAD

**Issue by gwpl** [charmbracelet/mods#235]
As example step number one and inspiration, imagine:

```
cat file | mods --pattern fabric:extract_wisdom
```

that would fetch (or use cached) pattern from https://github.com/danielmiessler/fabric/tree/main/patterns and use it.

Of course this could be extended in future to other providers.

(Maybe it's actually worth to be project by itself and be modular, sth like "pattern provider" from which tools like this one could get patterns/prompts etc...)

cross-linking: https://github.com/TheR1D/shell_gpt/issues/518

**Comment by caarlos0** [comment]
would https://github.com/charmbracelet/mods/pull/245 do it?

you can do things like:

```yaml
roles:
  "create_summary":
    - https://raw.githubusercontent.com/danielmiessler/fabric/main/patterns/create_summary/system.md
```

wdyt?
