### ISSUE TITLE
Add Groq config in mods.yml

### ISSUE THREAD

**Issue by ye-rm** [charmbracelet/mods#240]
``` 
  groq:
    base-url: https://api.groq.com/openai/v1
    api-key-env: GROQ_API_KEY
    models:
      mixtral-8x7b-32768:
        aliases: ["mix"]
        max-input-chars: 12250
        fallback:
      llama2-70b-4096:
        aliases: ["lla2"]
        max-input-chars: 12250
        fallback:
```
I tried to config [Groq](https://console.groq.com/docs/quickstart) like above, these two models worked.
I guess the `aliases` and `max-input-chars` according to other configs, could someone confirm these so we can consider integrating them into the default configuration.
