### ISSUE TITLE
Bug: Attempting to continue conversation with Ollama model will fallback to default model

### ISSUE THREAD

**Issue by nshern** [charmbracelet/mods#263]
**Describe the bug**
When attempting to continue the conversation with an Ollama-based model, it will automatically fall back to the default model instead of continuing the conversation with Ollama.

**Setup**
Please complete the following information along with version numbers, if applicable.
 - OS: macOS 14.4.1
 - Shell: fish
 - Terminal Emulator: WezTerm
 - Terminal Multiplexer: WezTerm

**To Reproduce**
1. Type `mods --setings`
2. Insert:
```
apis:
  openai:
    base-url: https://api.openai.com/v1
    models:
      gpt-4:
        aliases: ["4"]
        max-input-chars: 24500
        fallback: gpt-3.5-turbo
  ollama:
    base-url: http://localhost:11434/v1
    api-key-env: NA
    models:
      "llama3:8b":
        aliases: ["llama3"]
        max-input-chars: 4000
default-model: gpt-4
```
3. install ollama
4. run `ollama pull llama3:8b`
5. type `mods -M`
6. choose llama3:8b
7. type whatever
8. run `mods -C` or `mods -<SHA>` 
9. see that it is falling back to default GPT-4k
10. See error
