### ISSUE TITLE
Ollama/llama3: ERROR  Unknown API error.

### ISSUE THREAD

**Issue by mrusme** [charmbracelet/mods#276]
**Describe the bug**
The Ollama integration (using llama3:latest) doesn't appear to be working.

**Setup**
 - OS: Gentoo Linux
 - Shell: Zsh
 - Terminal Emulator: Alacritty

**To Reproduce**
1. Install mods@main
2. Add the configuration for Ollama as shown in https://github.com/charmbracelet/mods/pull/256
3. `mods -M` and select `llama3`
4. Write a prompt

**Expected behavior**
mods should query the Ollama instance and return a response.

**Current behavior**
mods shows:

```
   ERROR  Unknown API error.
```

`ollama serve` shows:

```
[GIN] 2024/05/31 - 10:27:12 | 404 |     154.422µs |       127.0.0.1 | POST     "/api/chat"
```

**Additional context**
Not sure how https://github.com/charmbracelet/mods/issues/162 plays into what was done in https://github.com/charmbracelet/mods/pull/256

**Comment by piero-vic** [comment]
The configuration file in #256 uses `llama3:70b`. `llama3:latest` downloads the 8b version. I think the configuration should match the downloaded version of the model. Both of these two configuration worked for me.

```yml
  ollama:
    base-url: http://localhost:11434/api
    models:
      'llama3':  # Instead of 'llama3:70b'
        aliases: ["llama3"]
        max-input-chars: 650000
```

```yml
  ollama:
    base-url: http://localhost:11434/api
    models:
      'llama3:latest': # Instead of 'llama3:70b'
        aliases: ["llama3"]
        max-input-chars: 650000
```
