### ISSUE TITLE
max-input-chars is required for each model despite global config

### ISSUE THREAD

**Issue by philippgille** [charmbracelet/mods#306]
It appears that the `max-input-chars` is required for each model, even if it's configured at the root level of the config, where I expected it to apply as a default to all models.

I noticed this when trying to add Mistral as a provider to the config as part of https://github.com/charmbracelet/mods/issues/174.

It's reproducible with the current latest mods v1.4.1, using the latest config template and just a removed `max-input-chars` from the models. Here's an example config based on the template:

```yaml
default-model: gpt-4
format-text:
  markdown: '{{ index .Config.FormatText "markdown" }}'
  json: '{{ index .Config.FormatText "json" }}'
roles:
  "default": []
format: false
role: "default"
raw: false
quiet: false
temp: 1.0
topp: 1.0
no-limit: false
word-wrap: 80
include-prompt-args: false
include-prompt: 0
max-retries: 5
fanciness: 10
status-text: Generating
max-input-chars: 12250
apis:
  openai:
    base-url: https://api.openai.com/v1
    api-key:
    api-key-env: OPENAI_API_KEY
    models:
      gpt-4o:
        aliases: ["4o"]
        fallback: gpt-4
      gpt-4:
        aliases: ["4"]
        fallback: gpt-3.5-turbo
```

Note that GPT-4 (without "o") is still the default model in the template as of today - I'll create a separate PR to switch that to the "o" version.

Then run: `mods -m 4o "Why is the sky blue?"`

It will output:

```
  Hello! How can I assist you today?                                          

   ERROR  There was a problem writing b236dabf77fcc4afef617d46d0798fd9f4e3d661 to the cache. Use  --no-cache  /  NO_CACHE  to disable it.  

  Save: constraint failed: CHECK constraint failed: title <> '' (275)
```

Note that just `mods "Why is the sky blue?"` works fine with that config, so it's as if the root level max-input-chars config only applies to the default model, instead of all. But that's not the intended behavior, right?
