### ISSUE TITLE
Github Copilot: "bad request: unknown integration"

### ISSUE THREAD

**Issue by nathabonfim59** [charmbracelet/mods#407]
**Describe the bug**
When I try to use Github Copilot as my provider, I get the error "Unknown integration"

**Setup**
Please complete the following information along with version numbers, if applicable.
 - OS [Linux pop-os 6.9.3-76060903-generic #202405300957~1732141768~22.04~f2697e1 SMP PREEMPT_DYNAMIC Wed N x86_64 x86_64 x86_64 GNU/Linux]
 - Shell [bash]
 - Terminal Emulator [wezterm]
 - Terminal Multiplexer [tmux]

**To Reproduce**
1. Configure GitHub copilot as your provider (config attached)
2. Run any command like
```sh
mods Hello
```

**Source Code**
> **Config file**

```yaml
default-model: gpt-4o
format-text:
  markdown: 'Format the response as markdown without enclosing backticks.'
  json: 'Format the response as json without enclosing backticks.'
roles:
  "default": []
format: false
role: "default"
raw: false
quiet: false
temp: 1.0
topp: 1.0
topk: 50
no-limit: false
word-wrap: 80
include-prompt-args: false
include-prompt: 0
max-retries: 5
fanciness: 10
status-text: Generating
theme: charm
max-input-chars: 12250
apis:
  copilot:
    base-url: https://api.githubcopilot.com
    models:
      gpt-4o:
        max-input-chars: 392000
      gpt-3.5-turbo:
        aliases: ["35t"]
        max-input-chars: 12250
        fallback: gpt-3.5
      claude-3.5-sonnet:
        aliases: ["claude3.5-sonnet", "claude-3-5-sonnet", "sonnet-3.5"]
        max-input-chars: 680000
```

**Expected behavior**

**Screenshots**
> **Error**
> ![image](https://github.com/user-attachments/assets/d275b2a6-7b44-43e8-9c50-3c6746818d94)

> **Request**
> ![image](https://github.com/user-attachments/assets/bd1d1298-7666-40a5-8d3f-1e4e21b9777b)

> **Response**
> ![image](https://github.com/user-attachments/assets/b9bb7b45-0443-42d7-be86-2eeb26296b72)
