### ISSUE TITLE
Support DeepSeek-R1 search engine

### ISSUE THREAD

**Issue by wwxiaoqi** [charmbracelet/mods#424]
**Is your feature request related to a problem? Please describe.**
I have reviewed the configurations related to DeepSeek. The relevant descriptions in https://github.com/charmbracelet/mods/pull/312 are too outdated. For example, the deepseek-code model has been replaced by deepseek-reasone. 

```
apis:
  # DeepSeek
  # https://api-docs.deepseek.com/zh-cn/
  deepseek:
    base-url: https://api.deepseek.com/
    api-key:
    api-key-env: DEEPSEEK_API_KEY
    models:
      deepseek-chat:
        aliases: ["chat"]
        max-input-chars: 384000
      deepseek-reasoner:
        aliases: ["r1"]
        max-input-chars: 384000
```

**Describe the solution you'd like**
Unfortunately, deepseek-reasoner does not comply with OpenAI's API specifications, only deepseek-chat does. Therefore, a completely new custom provider is needed to handle them separately. It must be integrated according to the description in the documentation. 
[deepseek docs API](https://api-docs.deepseek.com/zh-cn/guides/reasoning_model)

**Describe alternatives you've considered**
At present, my only alternative is to use it through a browser.
