### ISSUE TITLE
Multiple ollama config with different base-url

### ISSUE THREAD

**Issue by ArthurSaintDenis2** [charmbracelet/mods#431]
I currently have a setup where I can run ollama both on my laptop (for small models) an my desktop (for bigger models).

I tried using a config like this one:

```yaml
ollama-desktop:
  base-url: http://192.168.1.15:11434/api
  models:
    "deepseek-r1:14b":
      aliases: ["deepseek"]
      max-input-chars: 650000
    "deepseek-r1:32b":
      aliases: ["deepseek-big"]
      max-input-chars: 650000
ollama-local:
  base-url: http://localhost:11434/api
  models:
    "deepseek-r1:1.5b":
      aliases: ["deepseek"]
      max-input-chars: 650000
    "llama3.2:1b":
      aliases: ["llama"]
      max-input-chars: 650000
```

But I always get `ERROR  OpenAI authentication failed`.
It seems like ollama only works if the api is named "ollama". I can get around it by changing the names of the apis to only have one with the name ollama but this means I have to edit the config every time I want to change model.

Is there a way to achieve this ?
