### ISSUE TITLE
Feature: Different models for different roles

### ISSUE THREAD

**Issue by vanyauhalin** [charmbracelet/mods#432]
**Is your feature request related to a problem? Please describe.**

Each model handles the task differently. Using different models to solve different problems using roles sounds logical.

**Describe the solution you'd like**

```yml
roles:
  grammar:
    model: gpt-4o
    promt: []
```

Clear, intuitive, but brakes compatibility.

**Describe alternatives you've considered**

```yml
roles:
  grammar: []
  grammar-model: gpt-4o
```

Wierd, non-intuitive, but keeps compatibility.

**Additional context**

-
