### ISSUE TITLE
MCP support?

### ISSUE THREAD

**Issue by dexhorthy** [charmbracelet/mods#459]
yo - love mods! My favorite flag is --continue - love being able to access named conversations about the various (~20) different threads I'm following. 

I'd love to be able to use it for tools. I probably don't have the bandwidth to tackle this solo but would love to help out however I can.

**Is your feature request related to a problem? Please describe.**

I want to be use a cli to invoke llm actions against mcp servers, for example

```
mods [flags to specify mcp servers] can you make a linear ticket for austin to stock the fridges
```

**Describe the solution you'd like**

something that lets me opt in to exposing MCP tools to claude

```shell
mods --mcp-servers-config-json=path_to_servers.json --mcp-servers=linear  can you make a linear ticket for austin to stock the fridges with healthy snacks
```

or configure the path to servers json in global config profiles, e.g.

```yaml
# mods.yml
---
# List of predefined mcp server sets
mcp:
  servers_config_json: ~/.config/mcp/servers.json # could also see allowing a list of files
  server-sets:
    # use the linear server
    linear-and-github-tools:
      - linear
      - github
    just-linear:
      - linear

# set the default mcp server 
default-mcp-server-set: linear-and-github-tools
```
and in ~/.config/mcp/servers.json

```json
{
  "mcpServers": {
    "sqlite": {
      "command": "uvx",
      "args": ["mcp-server-linear"]
    },
    "git": {
      "command": "uvx",
      "args": ["mcp-server-github"]
    }

  }
}
```

then you get a tighter cli invocation 

```shell
mods -m claude-sonnet --mcp-tools linear can you make a linear ticket for austin to stock the fridges
```

(not sure what the short flag, maybe `-T` for tools?)

```shell
mods -m claude-sonnet -T google-gmail -T google-calendar can you find my last email from terri and send a calendar invite for the time we agreed on?
```

or maybe csv

```shell
mods -m claude-sonnet -T google-gmail,google-calendar can you find my last email from terri and send a calendar invite for the time we agreed on?
```

**Describe alternatives you've considered**

Use a different CLI, claude code, claude desktop, `mcp-cli` etc

**Additional context**

Let me know what else would be helpful!
