### ISSUE TITLE
OpenRouter compatibility?

### ISSUE THREAD

**Issue by nickali** [charmbracelet/mods#497]
### Describe the bug

Trying to use OpenRouter, I keep getting an "Invalid openrouter API key." error.

### Setup

Trying this out on MacOS 15.4.1.

### To Reproduce

In mods.yml,

```
apis:
  openrouter:
    base-url: https://openrouter.ai/api/v1
    api_key:
    apii-key-env: OPENROUTER_API_KEY
    models:
      google/gemini-2.5-pro-preview:
        aliases: ["gemini-pro"]
        max-input-chars: 600000
```

The OPENROUTER_API_KEY environment variable is set with the API key.

I've tried setting the api_key instead, but I get the same error.
