### ISSUE TITLE
MCP fails with openai models

### ISSUE THREAD

**Issue by jzyinq** [charmbracelet/mods#512]
### Describe the bug

Regarding latest MCP feature https://github.com/charmbracelet/mods/pull/486

MCP fails when using one of the openai models, works well while using anthropic models.

### Setup

Please complete the following information along with version numbers, if applicable.
 - OS Linux Mint
 - Shell zsh
 - Terminal Emulator guake
 - Terminal Multiplexer tmux

### To Reproduce

- Build latest version (768fa2b) locally
- Add configuration with valid token for example mcp server:
```yaml
mcp-servers:
  github:
    command: docker
    env:
      - GITHUB_PERSONAL_ACCESS_TOKEN=your_token
    args:
      - run
      - "-i"
      - "--rm"
      - "-e"
      - GITHUB_PERSONAL_ACCESS_TOKEN
      - "ghcr.io/github/github-mcp-server"
```
- Run mods with an openai model:
`./dist/mods --model gpt-4o-mini "how many stars have charmbracelet/mods project"`

- Observe output:
```
❯ ./dist/mods --model gpt-4o-mini "how many stars have charmbracelet/mods project"


  │ Ran tool:  github_search_repositories
  │
  │ Failed:
  │
  │   missing required parameter: query
```

### Expected behavior

MCP is properly called and handled

### Screenshots

![Image](https://github.com/user-attachments/assets/53ad0863-6005-4658-be8d-92fdec13371e)
