### ISSUE TITLE
Always partial results with Gemini 2.5 Flash models

### ISSUE THREAD

**Issue by alexgorbatchev** [charmbracelet/mods#515]
### Describe the bug

I found that using any gemini 2.5 flash models produces partial output. I can't tell if it's how it comes from the api or if the implementation is faulty, but that happens 100% of the time for me. I've tested with various OpenAI models and don't see this problem. Gemini Pro also produces full output.

### Setup

```
mods version v1.7.0 (c4461d4)
```

```
  google:
    models:
      gemini-2.5-flash-preview-05-20:
        aliases: ["flash05"]
        max-input-chars: 392000
      gemini-2.5-flash-preview-04-17:
        aliases: ["flash04"]
        max-input-chars: 392000
```

### To Reproduce

run `mods` with either model

### Expected behavior

Should produce full output

### Screenshots

```
 f22iagw f1vx9l62 fzwjdtt"><span class="fui-Text ___12hoepl_1o2irk0## Problem 1
* TEST FILE: src/layout/__tests__/List.test.tsx:87
* ERROR MESSAGE:
  expect(element).toHaveFocus()

      Expected element with focus:
      ...\n      Received element with focus:\n      ... // HTML content follows
* HTML:
  Expected element with focus:
    <div
      aria-selected="false"
      class="fui-ListItem ..."
      data-tabster="..."
      id="Alice Smith"
      role="row"
      tabindex="0"
    >
      <i
```
